In [2]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6]])
ar
ar.shape

(2, 3)

In [8]:
ar = np.array([[1, 2, 3], [4, 5, 6]])
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
mat = np.arange(0, 100, 5).reshape(4, 5)
mat.size

20

In [9]:
e = np.array([25, 50, 4, 5, 70, 20])
np.max(e)
np.min(e)
e.itemsize
# np.sum(e)

4

In [10]:
r = np.zeros(50).reshape(5, 10)
r
rr = np.ones(100).reshape(10, 10)
rr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
s = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
np.random.shuffle(s)
s

array([[10, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  2,  3]])